[package]
name = "rust-web-app-project-collaborative-document-editing"
version = "0.1.0"
edition = "2018"

[dependencies]
actix = "0.13.3"
actix-files = "0.6.6"
actix-rt = "2.9.0"
actix-web = "0.6.6"
actix-web-actors = "4.3.1"
actix_rt = "2.9.0"

